//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;

    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsInterestedIncSharp { get; set; }
        public Nullable<bool> IsInterestedInJava { get; set; }
        public Nullable<bool> IsInterestedInRuby { get; set; }
        public Nullable<int> CityId { get; set; }
        public SelectList CityList { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ImagePath { get; set; }
        public HttpPostedFileBase UserImageFile { get; set; }
        public string Role { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
    }
}
