//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProducId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CategoryId { get; set; }
    }
}
